### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by aureliendossantos** [aureliendossantos/new-miami-2080#1]
### Prog
- [x] Problème spawn niveau 2?
- [x] Le premier niveau hard n'est pas designé mais quand même lancable
- [x] le deuxieme threat hard débloqué avec le premier etait le boss
- [ ] Texte 1re fois shop
### Sons
- [x] Navigation et validation sur la map
- [x] Nouvelle threat ajoutée
- [ ] sons armes secondaires
### Contenu
- [x] Description des vaisseaux
- [ ] Niveaux
Ne pas hésiter à réutiliser des chunks de vague qui marchent bien plusieurs fois, c'est pas mal vu et c'est efficace, au contraire ça permet de s'entrainer dessus.
  - [x] Boss moyen
  - [ ] 2 difficiles
5-Horizontal Laser
Ajuster la bullet wheel tight et lui donner un ennemi
Egalement, vagues de swarm de petits ennemis ça surprend et ça fait mal en vrai
  - [ ] Boss difficile
